# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

devices = ["iPhone X", "iPhone SE"]

platform :ios do
  before_all do
    ensure_xcode_version(version: "10.1")
    setup_circle_ci
  end

  desc "Description of what the lane does"
  lane :format do
    sh "cd ../; ./Pods/SwiftFormat/CommandLineTool/swiftformat MyMorningCoffee --config .swiftformat"
    sh "cd ../; ./Pods/SwiftFormat/CommandLineTool/swiftformat MyMorningCoffeeTests --config .swiftformat"

    swiftlint(
      mode: "autocorrect",
      executable: "Pods/SwiftLint/swiftlint",
      config_file: ".swiftlint.yml",
    )

    swiftlint(
      mode: "lint",
      executable: "Pods/SwiftLint/swiftlint",
      config_file: ".swiftlint.yml",
    )
  end

  desc "run all tests"
  lane :test do
    scan(
      workspace: "MyMorningCoffee.xcworkspace",
      scheme: "MyMorningCoffee",
      devices: devices,
      disable_concurrent_testing: true,
      clean: false,
    )
  end

  desc "run all tests (skip build)"
  lane :test_no_build do
    scan(
      devices: devices,
      test_without_building: true,
      derived_data_path: "DerivedData",
    )
  end

  desc "generate app icon"
  lane :assets do
    appicon(
      # appicon_image_file: "fastlane/metadata/app_icon.png",
      appicon_devices: [:iphone, :ios_marketing],
      appicon_path: "MyMorningCoffee/Assets.xcassets",
    )
  end
end
