# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    ensure_xcode_version(version: "10.1")
    setup_circle_ci
  end

  desc "Description of what the lane does"
  lane :format do
    sh "cd ..; ./Pods/SwiftLint/switflint autocorrect"
    sh "cd ..; ./Pods/SwiftLint/switflint lint"
  end

  desc "run all tests"
  lane :test do
    scan(
      devices: ["iPhone X", "iPhone SE"],
    )
  end
end
